config/routes.rb
Trasys::Application.routes.draw do
  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"
  
  resources :users, :tickets, :sessions

  root :to => 'pages#index'

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  attr_accessible :body, :department, :email, :name, :status, :subject, :owner, :reply
  
  validates :name, :email, :subject, :body, :presence => true
  before_save :default_values
  
  def default_values
    self.status ||= 'Waiting for Staff Response'
  end  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :username, :password
  
  def self.authenticate(username, password)
    user = User.find(:first, :conditions => {:username => username})
    if user && user.password = password
      user
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.authenticate(params[:username], params[:password])
    if user
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged In!"
    else
      render "new"
    end  
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged Out!"
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all(conditions: {status: params[:status]})
  end
  
  
  def new
    @ticket = Ticket.new
  end
  
  
  def create
    @ticket = Ticket.new(params[:ticket])
    if @ticket.save
      redirect_to root_path, notice: 'Your ticket was sended. Please check your email for link on your ticket.'
      UserMailer.send_link(@ticket).deliver
    else
      render "new"
    end
  end
  
  
  def edit
    @ticket = Ticket.find(params[:id])
  end
  
  
  def update
    @ticket = Ticket.find(params[:id])
    
    if @ticket.update_attributes(params[:ticket])
      redirect_to tickets_path, notice: 'Ticket updated'
      UserMailer.send_changes(@ticket).deliver
    else
      render "edit"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/layouts/application.html.haml
!!!
%html{ html_attrs('en') }
  %head
    %title Trasys
    %meta(http-equiv="Content-Type" content="text/html; charset=utf-8")
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
  %body
    #wrapper
      #header        
        #logo
        #login_regist
          - if current_user
            %ul
              %li= current_user.username
              %li= link_to "Log Out", log_out_path
          - else
            %ul
              %li= link_to "Login", new_session_path
              %li Sign Up
        %ul#menu
          %li Home
          %li About Us
          %li Career
          %li Benefits
          %li Vacancies
          - if current_user
            %li= link_to "All Tickets", tickets_path(status: "Waiting for Staff Response")
          - else
            %li= link_to "Send Ticket", new_ticket_path
      - flash.each do |key, value|
        %p#notice= value
      = yield
      #footer
        %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit,
        %p sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat.
        %p 2012

app/views/pages/index.html.haml
#content
  #slider
  #text_blocks
    .text_block
      %h2 Information
      %p Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat. Ut wisis enim ad minim veniam, quis nostrud exerci tution ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat. Ut wisis enim ad minim veniam, quis nostrud exerci tution ullamcorper suscipit lobortis nisl ut aliquip ex ea commodo consequat.
    .text_block
      %h2 Events
      %ul
        %li Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat.
        %li Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat.
        %li Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat.
    .text_block
      %h2 Our news
      %ul
        %li Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat.
        %li Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat.
        %li Lorem ipsum dolor sit amet, consectetuer adipiscing elit, sed diem nonummy nibh euismod tincidunt ut lacreet dolore magna aliguam erat volutpat.
    .clearfix

app/views/tickets/edit.html.haml
#edit_ticket
  %h2= @ticket.subject
  %p.ticket_body= @ticket.body
  %p.ticket_footer
    Author:
    = @ticket.name
    |
    Email:
    = @ticket.email
    %hr
  %p.ticket_status
    Status: 
    = @ticket.status
    - if @ticket.owner
      %br
      Owner:
      = @ticket.owner
  %hr
  %br
  = form_for @ticket do |t|
    %p
      = t.label "Change Status"
      %br
      = t.select(:status, ['', 'Waiting for Customer', 'On Hold', 'Cancelled', 'Completed'])
    %p
      = t.label "Choose The Owner"
      %br
      = t.select(:owner, ['','Call Center Department','Information Security','Human Resources','Financial Department'])
    %p
      = t.label :reply
      %br
      = t.text_area :reply
    %p
      = t.submit "Update Ticket"
      
    

app/views/tickets/index.html.haml
#all_tickets
  #tickets_bar
    %ul
      %li= link_to 'New unassigned tickets', tickets_path(status: "Waiting for Staff Response")
      %li= link_to 'Open Tickets', tickets_path(status: "On Hold")
      %li= link_to 'On hold tickets', tickets_path(status: "On Hold")
      %li= link_to 'Closed Tickets', tickets_path(status: "Completed")
  #tickets_items
    - @tickets.each do |t|
      %h2= t.subject
      %p.ticket_body= t.body
      %p.ticket_footer
        Author:
        = t.name
        |
        Email:
        = t.email
      %p.reply_link
        = link_to "Reply | Edit", edit_ticket_path(t)
      .clearfix
      %hr
  .clearfix
      

app/views/tickets/new.html.haml
#ticket_form
  %h2 Ticket Form
  %h5 Send Us Your Ticket And We Will Reply
  = form_for @ticket do |f|
    %p
      = f.label :name 
      %br
      = f.text_field :name
    %p
      = f.label :email
      %br
      = f.text_field :email
    %p
      = f.label :department
      %br
      = f.select(:department, ['Call Center Department','Information Security','Human Resources','Financial Department'])
    %p
      = f.label :subject
      %br
      = f.text_field :subject
    %p
      = f.label :description
      %br
      = f.text_area :body
    %p
      = f.submit "Send Ticket"